name: Clusterapi action testing

on:
  push:
    tags:
      - '*'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: action testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # for demo setup kind cluster. In production you will use your managed cluster
      - uses: engineerd/setup-kind@v0.4.0
      # Install CAPI Provider
      - uses: evalsocket/cluster-api-action/cluster-api@master
        with:
          kubeconfig: ${KUBECONFIG}
          capi-provider: 'aws'
          capi-provider-version: 'v0.6.0'
          capi-version : 'v0.3.9'
          secret: 'YXNkYmhqdmFz'
        id: capi-aws
      - uses: evalsocket/cluster-api-action/clusterctl@master
        with:
          clusterctl_version: 'v0.3.9'
        id: clusterctl
